In [5]:
import numpy
import scipy
import matplotlib
import pandas
import statsmodels
import seaborn
import sklearn

print("numpy:", numpy.__version__)
print("scipy:", scipy.__version__)
print("matplotlib:", matplotlib.__version__)
print("statsmodels:", statsmodels.__version__)
print("pandas:", pandas.__version__)
print("seaborn:", seaborn.__version__)
print("sklearn:", sklearn.__version__)

numpy: 1.23.5
scipy: 1.10.0
matplotlib: 3.7.0
statsmodels: 0.13.5
pandas: 1.5.3
seaborn: 0.12.2
sklearn: 1.2.1


In [11]:
5*6
2+2

4

In [9]:
print(2+2)
2+3
6*7

4


42

In [13]:
annual = 50000

In [14]:
annual/(40*52)

24.03846153846154

In [16]:
def hourly(annualwage):
    hourlywage = annualwage/(40*52)
    
    
    return hourlywage

In [17]:
hourly(60000)

28.846153846153847

In [18]:
my_hourly_wage = hourly(17000)

In [19]:
my_hourly_wage

8.173076923076923

In [20]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
my_annual_salaries = [0,1,2,3,4,5,6,7,8,9]

In [22]:
hourly_wages = []
for salary in my_annual_salaries:
    hourly_wages.append( hourly(salary) )
hourly_wages

[0.0,
 0.0004807692307692308,
 0.0009615384615384616,
 0.0014423076923076924,
 0.0019230769230769232,
 0.002403846153846154,
 0.0028846153846153848,
 0.0033653846153846156,
 0.0038461538461538464,
 0.004326923076923077]

In [23]:
annual/(40*52)

24.03846153846154

In [24]:
def is_roth_eligible(annual_wage):
    return annual_wage < 130000

In [25]:
def is_roth_eligible(annual_wage):
    if annual_wage < 130000:
        return True
    else:
        return False

In [26]:
200000 < 130000

False

In [27]:
is_roth_eligible(100000)

True

In [28]:
is_roth_eligible(200000)

False

In [29]:
hourly(my_annual_salaries)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [30]:
hourly_wages = numpy.array([1,2,3])

In [31]:
hourly_wages/60

array([0.01666667, 0.03333333, 0.05      ])

In [32]:
numpy.abs([-1,2,3])

array([1, 2, 3])

In [33]:
numpy.abs(numpy.array([-1,2,3]))

array([1, 2, 3])

In [34]:
numpy.sum([-1,2,3])

4

In [35]:
for i in range(1000):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27